tasks:
- init: >
    python3 -m venv .venv && 
    source .venv/bin/activate &&
    python3 -m pip install -r requirements.txt

vscode:
    extensions:
        - almenon.arepl
        - littlefoxteam.vscode-python-test-adapter@0.3.16:tZ/6xOSSdKUaq6JCUVkD+A==